# main text of home
name: Burak Ekici
bio: Developer, Blogger, CS Student

# twitter summary info
description: Personal blog and portfolio page 

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.jpg

# If you want to include your resume, set to true
# and specify source (external or local).
resume: true
resume-external: true
# resume-url: http://burakekici.com/resume.pdf
resume-url: assets/resume.pdf

url: https://burakekici.github.io
# your url: http://USERNAME.github.io

permalink: /:title/

# To enable google analytics, supply your token below
analytics-google: 'UA-52187271-4'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, leave categories empty
disqus:
  shortname: bekici # enter this from your disqus account
  categories: [blog, project] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
#facebook: burakekici0
twitter: burakekici0
linkedin: burakekici
github: burakekici
spotify: bekici
email: contact.ekici@gmail.com
# medium: ekici
# google: burakekici0
# instagram: burakekici0
# pinterest: burakekici
# youtube: burakekici0
# quora: Burak-Ekici-2
# vimeo: burakekici
# stackoverflow: 7044681/mystackoverflow
# reddit: username
# lastfm: mylastfm
# lanyrd: mylanyrd

authors:
    johndoe:
        name: Burak Ekici
        bio: Computer science student
        external-image: false
        picture: assets/images/profile.jpg
        twitter: burakekici0

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
#projects: true

# if you don't need "about" or "blog", comment them out below
about: true
blog: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: true

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin

jekyll-mentions:
    base_url: https://github.com
